export const ADS_CONFIG = {
  PER_BATCH: 15,
  TOTAL_ADS: 195,
  MAX_BATCHES: Math.ceil(195 / 15) 
} as const;

export const ADS_PER_BATCH = ADS_CONFIG.PER_BATCH;
export const TOTAL_ADS_AVAILABLE = ADS_CONFIG.TOTAL_ADS;
export const MAX_BATCHES = ADS_CONFIG.MAX_BATCHES;